# Configuration for Local Run
security.jwt.secret-key=mZ8K9vYwT2RrQ4pLx7uN3cFh6sJd1bXg5kLm8PqRsTu=
security.jwt.access-token-expiration=350000
security.jwt.refresh-token-expiration=604800000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.application.name=spring-security-crud-jwt

server.port=5000

spring.datasource.url=jdbc:mysql://localhost:3306/react_spring
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.web=DEBUG
logging.level.com.soumya.main=DEBUG

spring.jpa.open-in-view=false
security.jwt.issuer=springboot-crud-api
security.jwt.audience=com.soumya.spring-security

#server.ssl.enabled=true
##true enabled ssl (npw https),  false disabled (now http)
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tomcat

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100
